### ISSUE TITLE
PIP release date

### ISSUE THREAD

**Issue by jlevy44** [VarIr/scikit-hubness#1]
When will this package be released on pip? Seems really cool, especially with hnsw graph construction.

**Comment by jlevy44** [comment]
Also, any chance you could also include support for python 3.6?

**Comment by VarIr** [comment]
Dear @jlevy44,
thanks for your interest in `hubness`! This is currently under heavy development, and the API is not yet stable. Therefore, I'm hesitant to release on PyPI atm. However, you can already `git clone` it, and install it with `pip install -e .` from within the cloned directory.

I'll consider Python 3.6 support. So far, 3.7 is only required for delayed annotation evaluation.

**Comment by VarIr** [comment]
The package is now available on pypi.org under the new name of `scikit-hubness`.
Please try to install with `pip install scikit-hubness`. Please also report any issues you may encounter.

**Comment by jlevy44** [comment]
Awesome. Thanks @varlr !
