### ISSUE TITLE
Python version backward compatibility (to be able to use it in Google Colab)

### ISSUE THREAD

**Issue by j-bac** [VarIr/scikit-hubness#64]
Many thanks for this great package. It would be really nice if the package could be compatible with older Python, currently it is impossible to install or use it on Google Colaboratory

**Comment by VarIr** [comment]
Thanks for the feedback. It's a shame that Colab only provides outdated python.
I'll look into it. This would probably only require the PEP 563 "postponed evaluation of type annotations" to be removed.

**Comment by VarIr** [comment]
Now that [Colab has finally moved to 3.7](https://twitter.com/googlecolab/status/1365062244225060865), it should be possible to run scikit-hubness. I'll close this issue, but feel free to reopen, if it still doesn't work.
