### ISSUE TITLE
Compute metrics without NN lookup

### ISSUE THREAD

**Issue by mrdrozdov** [VarIr/scikit-hubness#66]
Hi, I've already pre-computed my nearest neighbors for a large dataset. Can I use Hubness to compute metrics (such as skewness) using this pre-computed neighbor list?

**Comment by VarIr** [comment]
Yes, this is possible by setting up a hubness analysis like this:
```
hub = Hubness(metric="precomputed")
hub.fit(X=distance_matrix)
hubness_estimates = hub.score()
```
where `distance_matrix` is your numpy array of precomputed distances.
