### ISSUE TITLE
class skhubness.neighbors.HNSW does not support distance type FLOAT

### ISSUE THREAD

**Issue by ivan-marroquin** [VarIr/scikit-hubness#70]
Hi,

I would like to report the following issue when using HNSW:

import numpy as np
from skhubness.neighbors import HNSW

X= np.random.randn(100,7)

index= HNSW(n_candidates= 10, metric= 'euclidean', method= 'hsnw')

index.fit(X)

The last command produces the following error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\neighbors\hnsw.py", line 106, in fit
    print_progress=(self.verbose >= 2))
RuntimeError: 2021-06-08 15:43:40 .\similarity_search\include\methodfactory.h:60 (similarity::MethodFactoryRegistry<float>::CreateMethod) It looks like the method hsnw is not defined for the distance type : FLOAT

Ivan

**Comment by VarIr** [comment]
It should work with method='h**ns**w'.
