### ISSUE TITLE
Error message: invalid value encountered in multiply

### ISSUE THREAD

**Issue by ivan-marroquin** [VarIr/scikit-hubness#72]
Hi,

I would like to report the following error message:

Warning (from warnings module):
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\neighbors\hnsw.py", line 154
    dtype=X.dtype) * np.nan
RuntimeWarning: invalid value encountered in multiply

I am still able to get some scores, would this error message influence the quality of the outputs?

To duplicate the issue, please refer to attached zip file.

Ivan

[issue_hubness_assessment.zip](https://github.com/VarIr/scikit-hubness/files/6631739/issue_hubness_assessment.zip)

**Comment by VarIr** [comment]
This is most likely no problem. These lines simply create arrays with dummy values that are later on overwritten.

**Comment by ivan-marroquin** [comment]
Thanks for the clarification
